const times = new Set()
times.add('Vasco')
times.add('Flamengo')
times.add('Vasco')
times.add('São Paulo').add('Palmeiras').add('Corinthians')
console.log(times)
console.log(times.size())
console.log(times.has('Vasco'))

times.delete('Flamengo')
